//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace WebTV.Model
{
    public partial class Log
    {
        #region Primitive Properties
    
        public virtual int PlayLogId
        {
            get;
            set;
        }
    
        public virtual int AnimationId
        {
            get { return _animationId; }
            set
            {
                if (_animationId != value)
                {
                    if (Animation != null && Animation.AnimationId != value)
                    {
                        Animation = null;
                    }
                    _animationId = value;
                }
            }
        }
        private int _animationId;
    
        public virtual System.DateTime PlayedAt
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Animation Animation
        {
            get { return _animation; }
            set
            {
                if (!ReferenceEquals(_animation, value))
                {
                    var previousValue = _animation;
                    _animation = value;
                    FixupAnimation(previousValue);
                }
            }
        }
        private Animation _animation;

        #endregion
        #region Association Fixup
    
        private void FixupAnimation(Animation previousValue)
        {
            if (previousValue != null && previousValue.Logs.Contains(this))
            {
                previousValue.Logs.Remove(this);
            }
    
            if (Animation != null)
            {
                if (!Animation.Logs.Contains(this))
                {
                    Animation.Logs.Add(this);
                }
                if (AnimationId != Animation.AnimationId)
                {
                    AnimationId = Animation.AnimationId;
                }
            }
        }

        #endregion
    }
}
