//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace WebTV.Model
{
    public partial class MediaGroup
    {
        #region Primitive Properties
    
        public virtual int MediaGroupId
        {
            get;
            set;
        }
    
        public virtual int MediaSetId
        {
            get { return _mediaSetId; }
            set
            {
                if (_mediaSetId != value)
                {
                    if (MediaSet != null && MediaSet.MediaSetId != value)
                    {
                        MediaSet = null;
                    }
                    _mediaSetId = value;
                }
            }
        }
        private int _mediaSetId;

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Media> Media
        {
            get
            {
                if (_media == null)
                {
                    var newCollection = new FixupCollection<Media>();
                    newCollection.CollectionChanged += FixupMedia;
                    _media = newCollection;
                }
                return _media;
            }
            set
            {
                if (!ReferenceEquals(_media, value))
                {
                    var previousValue = _media as FixupCollection<Media>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMedia;
                    }
                    _media = value;
                    var newValue = value as FixupCollection<Media>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMedia;
                    }
                }
            }
        }
        private ICollection<Media> _media;
    
        public virtual MediaSet MediaSet
        {
            get { return _mediaSet; }
            set
            {
                if (!ReferenceEquals(_mediaSet, value))
                {
                    var previousValue = _mediaSet;
                    _mediaSet = value;
                    FixupMediaSet(previousValue);
                }
            }
        }
        private MediaSet _mediaSet;

        #endregion
        #region Association Fixup
    
        private void FixupMediaSet(MediaSet previousValue)
        {
            if (previousValue != null && previousValue.MediaGroups.Contains(this))
            {
                previousValue.MediaGroups.Remove(this);
            }
    
            if (MediaSet != null)
            {
                if (!MediaSet.MediaGroups.Contains(this))
                {
                    MediaSet.MediaGroups.Add(this);
                }
                if (MediaSetId != MediaSet.MediaSetId)
                {
                    MediaSetId = MediaSet.MediaSetId;
                }
            }
        }
    
        private void FixupMedia(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Media item in e.NewItems)
                {
                    item.MediaGroup = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Media item in e.OldItems)
                {
                    if (ReferenceEquals(item.MediaGroup, this))
                    {
                        item.MediaGroup = null;
                    }
                }
            }
        }

        #endregion
    }
}
