//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace WebTV.Model
{
    public partial class MediaSet
    {
        #region Primitive Properties
    
        public virtual int MediaSetId
        {
            get;
            set;
        }
    
        public virtual int AnimationId
        {
            get { return _animationId; }
            set
            {
                if (_animationId != value)
                {
                    if (Animation != null && Animation.AnimationId != value)
                    {
                        Animation = null;
                    }
                    _animationId = value;
                }
            }
        }
        private int _animationId;
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> StartDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> EndDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Animation Animation
        {
            get { return _animation; }
            set
            {
                if (!ReferenceEquals(_animation, value))
                {
                    var previousValue = _animation;
                    _animation = value;
                    FixupAnimation(previousValue);
                }
            }
        }
        private Animation _animation;
    
        public virtual ICollection<Media> Media
        {
            get
            {
                if (_media == null)
                {
                    var newCollection = new FixupCollection<Media>();
                    newCollection.CollectionChanged += FixupMedia;
                    _media = newCollection;
                }
                return _media;
            }
            set
            {
                if (!ReferenceEquals(_media, value))
                {
                    var previousValue = _media as FixupCollection<Media>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupMedia;
                    }
                    _media = value;
                    var newValue = value as FixupCollection<Media>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupMedia;
                    }
                }
            }
        }
        private ICollection<Media> _media;

        #endregion
        #region Association Fixup
    
        private void FixupAnimation(Animation previousValue)
        {
            if (previousValue != null && previousValue.MediaSets.Contains(this))
            {
                previousValue.MediaSets.Remove(this);
            }
    
            if (Animation != null)
            {
                if (!Animation.MediaSets.Contains(this))
                {
                    Animation.MediaSets.Add(this);
                }
                if (AnimationId != Animation.AnimationId)
                {
                    AnimationId = Animation.AnimationId;
                }
            }
        }
    
        private void FixupMedia(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Media item in e.NewItems)
                {
                    item.MediaSet = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Media item in e.OldItems)
                {
                    if (ReferenceEquals(item.MediaSet, this))
                    {
                        item.MediaSet = null;
                    }
                }
            }
        }

        #endregion
    }
}
