//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace WebTV.Model
{
    public partial class WebTVContext : ObjectContext
    {
        public const string ConnectionString = "name=WebTVContext";
        public const string ContainerName = "WebTVContext";
    
        #region Constructors
    
        public WebTVContext()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public WebTVContext(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public WebTVContext(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Animation> Animations
        {
            get { return _animations  ?? (_animations = CreateObjectSet<Animation>("Animations")); }
        }
        private ObjectSet<Animation> _animations;
    
        public ObjectSet<Customer> Customers
        {
            get { return _customers  ?? (_customers = CreateObjectSet<Customer>("Customers")); }
        }
        private ObjectSet<Customer> _customers;
    
        public ObjectSet<Log> Logs
        {
            get { return _logs  ?? (_logs = CreateObjectSet<Log>("Logs")); }
        }
        private ObjectSet<Log> _logs;
    
        public ObjectSet<Media> Media
        {
            get { return _media  ?? (_media = CreateObjectSet<Media>("Media")); }
        }
        private ObjectSet<Media> _media;
    
        public ObjectSet<Property> Properties
        {
            get { return _properties  ?? (_properties = CreateObjectSet<Property>("Properties")); }
        }
        private ObjectSet<Property> _properties;
    
        public ObjectSet<PropertyDescriptor> PropertyDescriptors
        {
            get { return _propertyDescriptors  ?? (_propertyDescriptors = CreateObjectSet<PropertyDescriptor>("PropertyDescriptors")); }
        }
        private ObjectSet<PropertyDescriptor> _propertyDescriptors;
    
        public ObjectSet<MediaSet> MediaSets
        {
            get { return _mediaSets  ?? (_mediaSets = CreateObjectSet<MediaSet>("MediaSets")); }
        }
        private ObjectSet<MediaSet> _mediaSets;

        #endregion
    }
}
