//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace WebTV.Model
{
    public partial class Property
    {
        #region Primitive Properties
    
        public virtual int PropertyId
        {
            get;
            set;
        }
    
        public virtual int PropertyDescriptorId
        {
            get { return _propertyDescriptorId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_propertyDescriptorId != value)
                    {
                        if (PropertyDescriptor != null && PropertyDescriptor.PropertyDescriptorId != value)
                        {
                            PropertyDescriptor = null;
                        }
                        _propertyDescriptorId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _propertyDescriptorId;
    
        public virtual Nullable<int> MediaId
        {
            get;
            set;
        }
    
        public virtual string Value
        {
            get;
            set;
        }
    
        public virtual Nullable<int> MediaGroupId
        {
            get { return _mediaGroupId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_mediaGroupId != value)
                    {
                        if (MediaGroup != null && MediaGroup.MediaGroupId != value)
                        {
                            MediaGroup = null;
                        }
                        _mediaGroupId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _mediaGroupId;

        #endregion
        #region Navigation Properties
    
        public virtual PropertyDescriptor PropertyDescriptor
        {
            get { return _propertyDescriptor; }
            set
            {
                if (!ReferenceEquals(_propertyDescriptor, value))
                {
                    var previousValue = _propertyDescriptor;
                    _propertyDescriptor = value;
                    FixupPropertyDescriptor(previousValue);
                }
            }
        }
        private PropertyDescriptor _propertyDescriptor;
    
        public virtual MediaGroup MediaGroup
        {
            get { return _mediaGroup; }
            set
            {
                if (!ReferenceEquals(_mediaGroup, value))
                {
                    var previousValue = _mediaGroup;
                    _mediaGroup = value;
                    FixupMediaGroup(previousValue);
                }
            }
        }
        private MediaGroup _mediaGroup;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupPropertyDescriptor(PropertyDescriptor previousValue)
        {
            if (previousValue != null && previousValue.Properties.Contains(this))
            {
                previousValue.Properties.Remove(this);
            }
    
            if (PropertyDescriptor != null)
            {
                if (!PropertyDescriptor.Properties.Contains(this))
                {
                    PropertyDescriptor.Properties.Add(this);
                }
                if (PropertyDescriptorId != PropertyDescriptor.PropertyDescriptorId)
                {
                    PropertyDescriptorId = PropertyDescriptor.PropertyDescriptorId;
                }
            }
        }
    
        private void FixupMediaGroup(MediaGroup previousValue)
        {
            if (previousValue != null && previousValue.Properties.Contains(this))
            {
                previousValue.Properties.Remove(this);
            }
    
            if (MediaGroup != null)
            {
                if (!MediaGroup.Properties.Contains(this))
                {
                    MediaGroup.Properties.Add(this);
                }
                if (MediaGroupId != MediaGroup.MediaGroupId)
                {
                    MediaGroupId = MediaGroup.MediaGroupId;
                }
            }
            else if (!_settingFK)
            {
                MediaGroupId = null;
            }
        }

        #endregion
    }
}
